### ISSUE TITLE
Suggestion: use Twitter DM for notification.

### ISSUE THREAD

**Issue by MichaelKreil** [yetzt/nsa#1]
Allow NSA clients to add a list of twitter accounts during startup (e.g. ['jedi', 'skywalker']).
These accounts will be notified via direct message, when the service crashes.
The server needs a Twitter account and API key in the config, that will push the notifications. (e.g. {account: 'hansolo_nsa', key:'...'} )

(The registered twitter accounts have to follow the NSA server Twitter account.)

**Comment by yetzt** [comment]
it would make more sense, to implement a simple streaming interface for third party clients to tap into and not overload nsa with everything but a kitchen sink.

**Comment by yetzt** [comment]
this should go to nsa-server
